### ISSUE TITLE
Gevent Library Not Compatible with SSH Library

### ISSUE THREAD

**Issue by kstine** [eldaduzman/robotframework-gevent#94]
When combining SSH Library command with Gevent Library the error:
`SSHException: Error reading SSH protocol bannercannot switch to a different thread`
is thrown.

This is using python 3.10 on a windows 10 machine with a virtualenv.

Example:
```robot
*** Settings ***
Library    GeventLibrary
Library    SSHLibrary


*** Variables ***
${REMOTE_IP}    ip_address
${SSH_USERNAME}    username
${SSH_PASSWORD}    password

*** Test Cases ***
Gevent Test
    [Setup]  Login To VM
    [Teardown]  Close Connection
    Create Gevent Bundle    alias=gevent_test
    Add Coroutine    Log To Console    ASync function1    alias=gevent_test
    Add Coroutine    Log To Console    ASync function2    alias=gevent_test
    Run Coroutines    alias=gevent_test

*** Keywords ***
Setup
    Open Connection    ${REMOTE_IP}
    Login    ${SSH_USERNAME}    ${SSH_PASSWORD}
```

**Comment by eldaduzman** [comment]
Hi @kstine
I've looked into this bug more closely.

Gevent uses monkey patching to replace "blocking" code in the builtins with code that is more compatible with libuv so that it will not hug the event loop.

The problem this creates in the context of robotframework is with the threading module.

Robotframework runs  several threads for console reporting, timeout checks and other background works.
These threads are initiated at the beginning of the execution, so before we get the chance to apply the monkey patch.
These threads has some work to do when a library is being loaded, so the patching at this point can not include the patching of the threading module, as a result, the original implementation excluded the threading module altogether such that it is not patched.

Robotframework ssh library uses paramiko for ssh connection and it too uses threads to read the stdout from the channle.
The existence of an event loop makes it impossible for the library to perform a context switch using the OS or sys module.

So the combination of these 2 facts leads to a contradictory requirement - robotframework doesn't allow for the threading module to be patched, while ssh library requires for them to be patched.

The solution for that is to apply the patch after the gevent library is initiated, 
This way, the test will pass, but there will be an annoying error message at the end of the execution saying that a daemon thread wasn't shutdown (because the threading module is now patched).

To avoid inconvenience, I added a new importing parameter called "patch_thread".
When set to True, it will apply the thread library patching and allow you to use the ssh library.


In the long run, maybe I could workout a way to "unpatch" the threading module such that this annoying message will not appear, or conversely I could workout a monkey patch specific for the SSH library to allow it to be compliant with libuv without patching the entire threading module,
